config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  resources :courses, only: [:index, :show] do 
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :sections, only: [:update]
    resources :lessons, only: [:update]
    resources :sections, only: [] do
      resources :lessons, only: [:create]
    end
    resources :courses, only: [:new, :create, :show] do
      resources :sections, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	mount_uploader :image, ImageUploader


	belongs_to :user
	has_many :sections
	has_many :enrollments




 
validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}



  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end
  
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :course
	belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	belongs_to :section
	mount_uploader :video, VideoUploader

	  include RankedModel
	    ranks :row_order, with_same: :section_id


  def next_lesson
  	lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson  
end



end

app/models/section.rb
class Section < ApplicationRecord
	has_many :lessons
	belongs_to :course

	include RankedModel
  ranks :row_order, with_same: :course_id

    def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_many :courses
	has_many :photos
	has_many :enrollments
	has_many :enrolled_courses, through: :enrollments, source: :course


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
	 @courses = Course.all
	end
	def show
		@course = Course.find(params[:id])

	end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
	  before_action :authenticate_user!

	def show
	end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
before_action :authenticate_user!

  def create
   if current_course.premium?
    # Amount in cents
    @amount = (current_course.cost * 100).to_i

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Flixter Premo Content',
      currency: 'usd'
    )
  end
  current_user.enrollments.create(course: current_course)
  redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path

  end

   private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_course, only: [:show]


	def new
		@course = Course.new
	end

  def create
   @course = current_user.courses.create(course_params)
  if @course.valid?    	
    	redirect_to instructor_course_path(@course)
else
      render :new, status: :unprocessable_entity
    end
	end

	def show
        @section = Section.new
        @lesson = Lesson.new
	end



	private

def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized
    end
  end

helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

	def course_params
		params.require(:course).permit(:title, :description, :cost, :image)
	end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_lesson, only: [:show]


	def show
	end

	private

def require_authorized_for_current_lesson
	if !current_user.enrolled_in?(current_lesson.section.course)
		redirect_to course_path(current_lesson.section.course), alert: 'You are not enrolled! Enroll to view!'
	end
end

	helper_method :current_lesson
	
	def current_lesson
		@current_lesson ||= Lesson.find(params[:id])
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

	  def privacy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/courses/index.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Learn something today</h1>
  <hr />



<% @courses.each do |course| %>
<h2 class="text-center">
<%= link_to course.title, course_path(course) %></h2>
<br />
<br />
<%= image_tag course.image.url, class: 'img-fluid' %>
<div class="row">
<div class="col-sm-8 col-12">
<%= course.description %>
</div>
<div class="col-4 col-12 text-center">
	<%= link_to 'More Details...', course_path(course), class: 'btn btn-primary btn-large' %>
</div>
 </div>

 

<br class="clr" />
<% end %>
</div>



 <!-- this_is_the_page_where_videos_post -->

app/views/courses/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1><%= @course.title %></h1>
  <br />
  <div class="row">
    <div class="col-sm-4 col-12">
      <span class="badge badge-default">
        <%= number_to_currency @course.cost %>
      </span>

      <% if current_user && current_user == @course.user %>
        <br />
        <br />
        <%= link_to 'Administer', instructor_course_path(@course), class: 'btn btn-danger btn-large' %>
      <% end %>
      <br />
      <br />

  <% if current_user %>
    <% if current_user.enrolled_in?(@course) %>
        <h3 class="badge badge-info">You Are Enrolled!</h3>
      <% else %>
          <% if @course.free? %>
        <%= link_to 'Enroll', course_enrollments_path(@course), class: 'btn btn-primary', method: :post %>
    <% else %>
<%= form_tag course_enrollments_path(@course) do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-email="<%= current_user.email %>"
          data-description="<%= @course.title %> (<%= number_to_currency @course.cost %>)"
          data-amount="<%= (@course.cost * 100).to_i %>"
          data-locale="auto"></script>
<% end %>
       <% end %> 
      <% end %>
    <% end %>
  <% else %>
    <h3 class="badge badge-info">Sign In or Sign Up to Enroll!</h3>
    </div>

    <div class="col-sm-8 col-12">
      <%= @course.description %>
    </div>
  </div>

  <div class="col-12">
<% @course.sections.each do |section| %>

      <br /><br />
      <div class="section">
        <h3>
        <%= section.title %>
      </h3>
<div class="row">
 <% section.lessons.rank(:row_order).each do |lesson| %>

<div class="col-12 col-sm-6">
       <div class="lesson text-center">
<br />
      <%= link_to lesson_path(lesson) do %>
              <b><%= lesson.title %></b>
              <br />
              <%= lesson.subtitle %>
            <% end %>
          </div>
          </div>
<br class="clr" />
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>